{% set name = "dakota" %}
{% set version = "6.17.0" %}

{% if blas_impl is undefined %}
{% set blas_impl = "openblas" %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: dakota{{ version }}.tar.gz
  url: https://dakota.sandia.gov/sites/default/files/distributions/public/dakota-{{ version }}-public-src-cli.tar.gz
  sha256: a6045784426b75d4981efcc1f243a5cd74dfcf29d4572927d6162a82a12757c6
  patches:
    # - patches/surfpack_py_bindings.patch
    - patches/python.patch
    - patches/tests.patch
    - patches/link_librt.patch
    - patches/boost_dll_import_symbol.patch
    # - patches/use_external_pybind11.patch

build:
  number: 0
  skip: true  # [win or osx or py<38]

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - openmpi
    # - pybind11
    - boost-cpp
    - libblas * *{{ blas_impl }}
    - libcblas * *{{ blas_impl }}
    - liblapack
    - {{ blas_impl }}
    - python
    - perl
    - numpy
    - swig
    - doxygen
    - gsl
    - hdf5
        # - trilinos  # needs newer trilinos
  run:
    - libblas * *{{ blas_impl }}
    - libcblas * *{{ blas_impl }}
    - liblapack
    - {{ blas_impl }}
    - boost-cpp
    - python
    - {{ pin_compatible("numpy") }}
        # - trilinos
test:
  files:
    - UQ.in
    - rosenbrock.py
  requires:
    - perl
  imports:
    - dakota
    - dakota.interfacing
    - dakota.interfacing.dprepro
  commands:
    - $PREFIX/share/dakota/test/dakota_test.perl --label-regex=AcceptanceTest
    - dakota -i UQ.in

about:
  home: https://dakota.sandia.gov
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: The Dakota project delivers software for optimization and uncertainty quantification.
  description: |
    The Dakota project delivers both state-of-the-art research and robust, 
    usable software for optimization and UQ. Broadly, the Dakota software's 
    advanced parametric analyses enable design exploration, model calibration, 
    risk analysis, and quantification of margins and uncertainty with computational
    models. The Dakota toolkit provides a flexible, extensible interface 
    between such simulation codes and its iterative systems analysis methods.
  doc_url: https://dakota.sandia.gov/sites/default/files/docs/{{ version }}-release/user-html/
  dev_url: https://dakota.sandia.gov/

extra:
  recipe-maintainers:
    - timsnyder
    - looooo
